version: '3.8'

services:
  as400_core:
    build: ./core_legacy
    container_name: as400_core
    ports:
      - "5001:5001"
    volumes:
      - ./core_legacy/database:/app/database
    networks:
      - private_onprem_net
  wildfly_integrador_api:
    build: ./middleware_onprem
    depends_on:
      - as400_core
    ports:
      - "8080:8080"
    environment:
      - ERP_URL=http://as400_core:5001/services/InsertaOG
      - ERP_UPDATE=http://as400_core:5001/services/ActualizaPersonal
    networks:
      - azure_net
      - private_onprem_net
    volumes:
      - ./database/:/app/database
  portal_viajes:
    build: ./portal_viajes_azure
    container_name: portal_viajes_appservices
    depends_on:
      - wildfly_integrador_api
    environment:
      - API_URL=http://integrador_api:8080/ejecutaFuncion
    networks:
      - azure_net
  fabric_monitor:
    build: ./transversal_analytics
    container_name: fabric_monitor
    volumes:
      - ./core_legacy/database:/app/database_legacy
      - ./database:/app/database
    depends_on:
      - as400_core
    environment:
      - PYTHONUNBUFFERED=1
  gestion_modulo:
    build: ./sap_mx
    container_name: gestion_nomina
    volumes:
      - ./core_legacy/database:/app/database
    command: python procesar_nomina.py
    networks:
      - backend_net
    environment:
      - PYTHONUNBUFFERED=1 
  portal_rrhh:
    build: ./portal_rrhh_azure
    container_name: portal_rrhh_appservices
    networks:
      - azure_net
    depends_on:
      - wildfly_integrador_api
  fullsteps_saas:
    build: ./fullstep_saas
    container_name: fullstep_sass
    depends_on:
      - wildfly_integrador_api
    networks:
      - azure_net
  sftp_aje:
    image: atmoz/sftp
    volumes:
      - ./sftp_data:/home/epiuse/upload
    ports:
      - "2222:22"
    networks:
      - azure_net
  lambda_handler:
    build: ./lambda_simurator
    volumes:
      - ./sftp_data:/data
    depends_on:
      - sftp_aje
      - as400_core
    networks:
      - azure_net
      - private_onprem_net
networks:
  azure_net:
  private_onprem_net:
  backend_net:
  